using Algoritmos.Algoritmos;

//Algoritmo1.Execute();
//Algoritmo2.Execute();
//Algoritmo3.Execute();
//Algoritmo4.Execute();
//Algoritmo5.Execute();
//Algoritmo6.Execute();
//Algoritmo7.Execute();
//Algoritmo8.Execute();
//Algoritmo9.Execute();
//Algoritmo10.Execute();
//Algoritmo11.Execute();
//Algoritmo12.Execute();
//Algoritmo13.Execute();
//Algoritmo14.Execute();
//Algoritmo15.Execute();
//Algoritmo16.Execute();
//Algoritmo17.Execute();
//Algoritmo18.Execute();
//Algoritmo18.Execute();
//Algoritmo19.Execute();
//Algoritmo20.Execute();
//Algoritmo21.Execute();
//Algoritmo22.Execute();
Algoritmo23.Execute();